version: "3.9"  # optional since v1.27.0
services:
    front-end:
        build: ./front-end
        ports:
            - "80:80"
    back-end:
        build: ./back-end 
        ports: 
            - "8000:8000"
